[project]
name = "os-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pexpect>=4.9.0",
    "pydantic>=2.10.5",
    "pydantic-ai>=0.0.19",
]
